---
# Addon config file.
# List out containers and the dockerfile that updates the container that is being built.
computeserver:
  dockerfiles: [Dockerfile]
programming:
  dockerfiles: [Dockerfile]
sas-casserver-primary:
  dockerfiles: [Dockerfile]
sas-viya-single-programming-only:
  dockerfiles: [Dockerfile]