---
# tasks file for SAS Viya service

- name: Set license directory
  set_fact:
    SASLICENSEDIR: "/opt/sas/viya/home/SASEventStreamProcessingEngine/current/etc/license/"

- name: Set license file
  set_fact:
    SASLICENSEFILE: "license.txt"

- name: Load the {{ role_name }} variables
  include_vars:
    file: "{{ role_name }}"
    name: sas_host_group_variables

- name: Install SAS packages
  include_role:
    name: sas-install

- name: Copy over entrypoint script
  template:
    src: entrypoint
    dest: "{{ SASHOME }}/bin/{{ role_name|lower }}-entrypoint.sh"
    mode: "0755"
    owner: "{{ INSTALL_USER }}"
    group: "{{ INSTALL_GROUP }}"

- name: Copy files to remote host
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ INSTALL_USER }}"
    group: "{{ INSTALL_GROUP }}"
    mode: 0755
  with_items:
  - { src: sas-espserver, dest: "{{ SASHOME }}/bin/sas-espserver" }
  - { src: sas-viya-espserver-default, dest: "/etc/init.d/sas-viya-espserver-default" }
