---
# Addon config file.
# List out containers and the dockerfile that updates the container that is being built.
omputeserver:
  dockerfile: [Dockerfile]
programming:
  dockerfile: [Dockerfile]
sas-casserver-primary:
  dockerfile: [Dockerfile]
single-programming-only:
  dockerfiles: [Dockerfile]