---
# tasks file for sas-casserver-primary

- name: Load the {{ role_name }} variables
  include_vars:
    file: "{{ role_name }}"
    name: sas_host_group_variables

- name: Install SAS packages
  include_role:
    name: sas-install

- name: Add cloud configuration files
  include_role:
    name: cloud-config

- name: Copy files to remote host
  copy:
    src: "{{ item.name }}"
    dest: "/opt/sas/viya/home/{{ item.path }}/{{ item.name }}"
    owner: "{{ INSTALL_USER }}"
    group: "{{ INSTALL_GROUP }}"
    mode: "{{ item.mode }}"
  with_items:
  - { name: createudfformats_startup.lua, path: "share/cas", mode: "0755" }
  - { name: register_cas.sh, path: "SASFoundation/utilities/bin", mode: "0755" }
  - { name: tenant_setup_docker.sh, path: "bin", mode: "0755" }

- name: configure cas server
  include_role:
    name: casserver-config
    tasks_from: start

- name: Copy over entrypoint script
  template:
    src: entrypoint
    dest: "{{ SASHOME }}/bin/{{ role_name }}-entrypoint.sh"
    mode: "0755"
    owner: "{{ INSTALL_USER }}"
    group: "{{ INSTALL_GROUP }}"
