---
# tasks file for pgpoolc
#
- name: Load the {{ role_name }} variables
  include_vars:
    file: "{{ role_name }}"
    name: sas_host_group_variables

- name: Install SAS packages
  include_role:
    name: sas-install

- name: Add cloud configuration files
  include_role:
    name: cloud-config

- name: Copy files to remote host
  copy:
    src: "{{ item.name }}"
    dest: "{{ SASHOME }}/{{ item.path }}/{{ item.name }}"
    owner: "{{ INSTALL_USER }}"
    group: "{{ INSTALL_GROUP }}"
    mode: "{{ item.mode }}"
  with_items:
  - { name: sas-pgpool, path: "bin", mode: "0755" }
  - { name: failover.sh, path: "share/pgpool-II", mode: "0755" }
  - { name: pcppass.ctmpl, path: "share/pgpool-II", mode: "0755" }
  - { name: pcp.conf.ctmpl, path: "share/pgpool-II", mode: "0755" }
  - { name: pgpool.conf.ctmpl, path: "share/pgpool-II", mode: "0755" }
  - { name: pool_hba.conf.ctmpl, path: "share/pgpool-II", mode: "0755" }
  - { name: pgpool_stop.sh, path: "libexec/sasdatasvrc/script", mode: "0755" }
  - { name: sds_consul_health_check.sh, path: "libexec/sasdatasvrc/script", mode: "0755" }
  
- name: Copy over entrypoint script
  template:
    src: entrypoint
    dest: "{{ SASHOME }}/bin/{{ role_name }}-entrypoint.sh"
    mode: "0755"
    owner: "{{ INSTALL_USER }}"
    group: "{{ INSTALL_GROUP }}"

