---
# tasks file for SAS Viya service

- name: Load the {{ role_name }} variables
  include_vars:
    file: "{{ role_name }}"
    name: sas_host_group_variables

- name: Install SAS packages
  include_role:
    name: sas-install

- name: Add cloud configuration files
  include_role:
    name: cloud-config

- name: Copy over entrypoint script
  template:
    src: entrypoint
    dest: "{{ SASHOME }}/bin/{{ role_name }}-entrypoint.sh"
    mode: "0755"
    owner: "{{ INSTALL_USER }}"
    group: "{{ INSTALL_GROUP }}"

- name: Post install build registry
  command: "runuser --shell \"/bin/sh\" --login sas --command \"{{ SPREHOME }}/SASFoundation/utilities/bin/post_install build_registry\" "

- name: Post install build default locale
  command: "runuser --shell \"/bin/sh\" --login sas --command \"{{ SPREHOME }}/SASFoundation/utilities/bin/post_install build_default_locale\" "

- name: Post install build samples config
  command: "runuser --shell \"/bin/sh\" --login sas --command \"{{ SPREHOME }}/SASFoundation/utilities/bin/post_install build_samples_config\" "

- block:
  - name: Install demouser
    include_role:
      name: auth-demo
  when: INCLUDE_DEMOUSER is defined
